version: '3.9'

services:

  web:
    image: nginx:alpine
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache

  php-cli:
    build:
      context: ./docker/php-cli
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache

  db:
    image: percona:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data

  adminer:
    image: adminer
    ports:
      - "8081:8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

volumes:
  db_data:
  composer:
